export const phoneNumbers = [
    { text: '🇺🇸 +1   United States', code: '+1', flag: '🇺🇸', country: 'US' },
    { text: '🇨🇦 +1   Canada', code: '+1', flag: '🇨🇦', country: 'CA' },
    { text: '🇷🇺 +7   Russia', code: '+7', flag: '🇷🇺', country: 'RU' },
    { text: '🇪🇬 +20  Egypt', code: '+20', flag: '🇪🇬', country: 'EG' },
    { text: '🇿🇦 +27  South Africa', code: '+27', flag: '🇿🇦', country: 'ZA' },
    { text: '🇬🇷 +30  Greece', code: '+30', flag: '🇬🇷', country: 'GR' },
    { text: '🇳🇱 +31  Netherlands', code: '+31', flag: '🇳🇱', country: 'NL' },
    { text: '🇧🇪 +32  Belgium', code: '+32', flag: '🇧🇪', country: 'BE' },
    { text: '🇫🇷 +33  France', code: '+33', flag: '🇫🇷', country: 'FR' },
    { text: '🇪🇸 +34  Spain', code: '+34', flag: '🇪🇸', country: 'ES' },
    { text: '🇭🇺 +36  Hungary', code: '+36', flag: '🇭🇺', country: 'HU' },
    { text: '🇮🇹 +39  Italy', code: '+39', flag: '🇮🇹', country: 'IT' },
    { text: '🇷🇴 +40  Romania', code: '+40', flag: '🇷🇴', country: 'RO' },
    { text: '🇨🇭 +41  Switzerland', code: '+41', flag:'🇨🇭', country: 'CH' },
    { text: '🇦🇹 +43  Austria', code: '+43', flag: '🇦🇹', country: 'AT' },
    { text: '🇬🇧 +44  United Kingdom', code: '+44', flag: '🇬🇧', country: 'GB' },
    { text: '🇩🇰 +45  Denmark', code: '+45', flag: '🇩🇰', country: 'DK' },
    { text: '🇸🇪 +46  Sweden', code: '+46', flag: '🇸🇪', country: 'SE' },
    { text: '🇳🇴 +47  Norway', code: '+47', flag:'🇳🇴', country: 'NO' },
    { text: '🇵🇱 +48  Poland', code: '+48', flag:'🇵🇱', country: 'PL' },
    { text: '🇩🇪 +49  Germany', code: '+49', flag: '🇩🇪', country: 'DE' },
    { text: '🇵🇪 +51  Peru', code: '+51', flag: '🇵🇪', country: 'PE' },
    { text: '🇲🇽 +52  Mexico', code: '+52', flag: '🇲🇽', country: 'MX' },
    { text: '🇨🇺 +53  Cuba', code: '+53', flag:'🇨🇺', country: 'CU' },
    { text: '🇦🇷 +54  Argentina', code: '+54', flag:'🇦🇷', country: 'AR' },
    { text: '🇧🇷 +55  Brazil', code: '+55', flag:'🇧🇷', country: 'BR' },
    { text: '🇨🇱 +56  Chile', code: '+56', flag:'🇨🇱', country: 'CL' },
    { text: '🇨🇴 +57  Colombia', code: '+57', flag:'🇨🇴', country: 'CO' },
    { text: '🇻🇪 +58  Venezuela', code: '+58', flag:'🇻🇪', country: 'VE' },
    { text: '🇲🇾 +60  Malaysia', code: '+60', flag:'🇲🇾', country: 'MY' },
    { text: '🇦🇺 +61  Australia', code: '+61', flag:'🇦🇺', country: 'AU' },
    { text: '🇮🇩 +62  Indonesia', code: '+62', flag:'🇮🇩', country: 'ID' },
    { text: '🇵🇭 +63  Philippines', code: '+63', flag:'🇵🇭', country: 'PH' },
    { text: '🇳🇿 +64  New Zealand', code: '+64', flag:'🇳🇿', country: 'NZ' },
    { text: '🇸🇬 +65  Singapore', code: '+65', flag:'🇸🇬', country: 'SG' },
    { text: '🇹🇭 +66  Thailand', code: '+66', flag:'🇹🇭', country: 'TH' },
    { text: '🇯🇵 +81  Japan', code: '+81', flag:'🇯🇵', country: 'JP' },
    { text: '🇰🇷 +82  South Korea', code: '+82', flag:'🇰🇷', country: 'KR' },
    { text: '🇻🇳 +84  Vietnam', code: '+84', flag:'🇻🇳', country: 'VN' },
    { text: '🇨🇳 +86  China', code: '+86', flag:'🇨🇳', country: 'CN' },
    { text: '🇹🇷 +90  Turkey', code: '+90', flag:'🇹🇷', country: 'TR' },
    { text: '🇮🇳 +91  India', code: '+91', flag:'🇮🇳', country: 'IN' },
    { text: '🇵🇰 +92  Pakistan', code: '+92', flag:'🇵🇰', country: 'PK' },
    { text: '🇦🇫 +93  Afghanistan', code: '+93', flag:'🇦🇫', country: 'AF' },
    { text: '🇱🇰 +94  Sri Lanka', code: '+94', flag:'🇱🇰',  country: 'LK' },
    { text: '🇲🇲 +95  Myanmar', code: '+95', flag:'🇲🇲', country: 'MM' },
    { text: '🇮🇷 +98  Iran', code: '+98', flag:'🇮🇷', country: 'IR' },
    { text: '🇲🇦 +212 Morocco', code: '+212', flag:'🇲🇦', country: 'MA' },
    { text: '🇩🇿 +213 Algeria', code: '+213', flag:'🇩🇿',  country: 'DZ' },
    { text: '🇹🇳 +216 Tunisia', code: '+216', flag:'🇹🇳',  country: 'TN' },
    { text: '🇱🇾 +218 Libya', code: '+218', flag:'🇱🇾', country: 'LY' },
    { text: '🇬🇲 +220 Gambia', code: '+220', flag:'🇬🇲', country: 'GM' },
    { text: '🇸🇳 +221 Senegal', code: '+221', flag:'🇸🇳', country: 'SN' },
    { text: '🇲🇷 +222 Mauritania', code: '+222', flag:'🇲🇷', country: 'MR' },
    { text: '🇲🇱 +223 Mali', code: '+223', flag:'🇲🇱', country: 'ML' },
    { text: '🇬🇳 +224 Guinea', code: '+224', flag:'🇬🇳', country: 'GN' },
    { text: '🇨🇮 +225 Ivory Coast', code: '+225', flag:'🇨🇮', country: 'CI' },
    { text: '🇧🇫 +226 Burkina Faso', code: '+226', flag:'🇧🇫',  country: 'BF' },
    { text: '🇳🇪 +227 Niger', code: '+227', flag:'🇳🇪',  country: 'NE' },
    { text: '🇹🇬 +228 Togo', code: '+228', flag:'🇹🇬',  country: 'TG' },
    { text: '🇧🇯 +229 Benin', code: '+229', flag:'🇧🇯', country: 'BJ' },
    { text: '🇲🇺 +230 Mauritius', code: '+230', flag:'🇲🇺', country: 'MU' },
    { text: '🇱🇷 +231 Liberia', code: '+231', flag:'🇱🇷', country: 'LR' },
    { text: '🇸🇱 +232 Sierra Leone', code: '+232', flag:'🇸🇱', country: 'SL' },
    { text: '🇬🇭 +233 Ghana', code: '+233', flag:'🇬🇭', country: 'GH' },
    { text: '🇳🇬 +234 Nigeria', code: '+234', flag:'🇳🇬', country: 'NG' },
    { text: '🇹🇩 +235 Chad', code: '+235', flag:'🇹🇩', country: 'TD' },
    { text: '🇨🇫 +236 Central African Republic', code: '+236', flag:'🇨🇫', country: 'CF' },
    { text: '🇨🇲 +237 Cameroon', code: '+237', flag:'🇨🇲', country: 'CM' },
    { text: '🇨🇻 +238 Cape Verde', code: '+238', flag:'🇨🇻',  country: 'CV' },
    { text: '🇸🇹 +239 Sao Tome and Principe', code: '+239', flag:'🇸🇹', country: 'ST' },
    { text: '🇬🇶 +240 Equatorial Guinea', code: '+240', flag:'🇬🇶', country: 'GQ' },
    { text: '🇬🇦 +241 Gabon', code: '+241', flag:'🇬🇦', country: 'GA' },
    { text: '🇨🇬 +242 Republic of the Congo', code: '+242', flag:'🇨🇬', country: 'CG' },
    { text: '🇨🇩 +243 Democratic Republic of the Congo', code: '+243', flag:'🇨🇩', country: 'CD' },
    { text: '🇦🇴 +244 Angola', code: '+244', flag:'🇦🇴', country: 'AO' },
    { text: '🇬🇼 +245 Guinea-Bissau', code: '+245', flag:'🇬🇼', country: 'GW' },
    { text: '🇮🇴 +246 British Indian Ocean Territory', code: '+246', flag:'🇮🇴', country: 'IO' },
    { text: '🇸🇨 +248 Seychelles', code: '+248', flag:'🇸🇨', country: 'SC' },
    { text: '🇸🇩 +249 Sudan', code: '+249', flag:'🇸🇩', country: 'SD' },
    { text: '🇷🇼 +250 Rwanda', code: '+250', flag:'🇷🇼', country: 'RW' },
    { text: '🇪🇹 +251 Ethiopia', code: '+251', flag:'🇪🇹', country: 'ET' },
    { text: '🇸🇴 +252 Somalia', code: '+252', flag:'🇸🇴', country: 'SO' },
    { text: '🇩🇯 +253 Djibouti', code: '+253', flag:'🇩🇯', country: 'DJ' },
    { text: '🇰🇪 +254 Kenya', code: '+254', flag:'🇰🇪', country: 'KE' },
    { text: '🇹🇿 +255 Tanzania', code: '+255', flag:'🇹🇿', country: 'TZ' },
    { text: '🇺🇬 +256 Uganda', code: '+256', flag:'🇺🇬', country: 'UG' },
    { text: '🇧🇮 +257 Burundi', code: '+257', flag:'🇧🇮', country: 'BI' },
    { text: '🇲🇿 +258 Mozambique', code: '+258', flag:'🇲🇿', country: 'MZ' },
    { text: '🇿🇲 +260 Zambia', code: '+260', flag:'🇿🇲', country: 'ZM' },
    { text: '🇲🇬 +261 Madagascar', code: '+261', flag:'🇲🇬',  country: 'MG' },
    { text: '🇷🇪 +262 Reunion', code: '+262', flag:'🇷🇪', country: 'RE' },
    { text: '🇿🇼 +263 Zimbabwe', code: '+263', flag:'🇿🇼', country: 'ZW' },
    { text: '🇳🇦 +264 Namibia', code: '+264', flag:'🇳🇦', country: 'NA' },
    { text: '🇲🇼 +265 Malawi', code: '+265', flag:'🇲🇼', country: 'MW' },
    { text: '🇱🇸 +266 Lesotho', code: '+266', flag:'🇱🇸', country: 'LS' },
    { text: '🇧🇼 +267 Botswana', code: '+267', flag:'🇧🇼', country: 'BW' },
    { text: '🇸🇿 +268 Eswatini', code: '+268', flag:'🇸🇿', country: 'SZ' },
    { text: '🇰🇲 +269 Comoros', code: '+269', flag:'🇰🇲', country: 'KM' },
    { text: '🇸🇭 +290 Saint Helena', code: '+290', flag:'🇸🇭', country: 'SH' },
    { text: '🇪🇷 +291 Eritrea', code: '+291', flag:'🇪🇷', country: 'ER' },
    { text: '🇦🇼 +297 Aruba', code: '+297', flag:'🇦🇼', country: 'AW' },
    { text: '🇫🇴 +298 Faroe Islands', code: '+298', flag:'🇫🇴', country: 'FO' },
    { text: '🇬🇱 +299 Greenland', code: '+299', flag:'🇬🇱', country: 'GL' },
    { text: '🇬🇮 +350 Gibraltar', code: '+350', flag:'🇬🇮', country: 'GI' },
    { text: '🇵🇹 +351 Portugal', code: '+351', flag:'🇵🇹', country: 'PT' },
    { text: '🇱🇺 +352 Luxembourg', code: '+352', flag:'🇱🇺', country: 'LU' },
    { text: '🇮🇪 +353 Ireland', code: '+353', flag:'🇮🇪', country: 'IE' },
    { text: '🇮🇸 +354 Iceland', code: '+354', flag:'🇮🇸', country: 'IS' },
    { text: '🇦🇱 +355 Albania', code: '+355', flag:'🇦🇱', country: 'AL' },
    { text: '🇲🇹 +356 Malta', code: '+356', flag:'🇲🇹', country: 'MT' },
    { text: '🇨🇾 +357 Cyprus', code: '+357', flag:'🇨🇾', country: 'CY' },
    { text: '🇫🇮 +358 Finland', code: '+358', flag:'🇫🇮', country: 'FI' },
    { text: '🇧🇬 +359 Bulgaria', code: '+359', flag:'🇧🇬', country: 'BG' },
    { text: '🇱🇹 +370 Lithuania', code: '+370', flag:'🇱🇹', country: 'LT' },
    { text: '🇱🇻 +371 Latvia', code: '+371', flag:'🇱🇻', country: 'LV' },
    { text: '🇪🇪 +372 Estonia', code: '+372', flag:'🇪🇪', country: 'EE' },
    { text: '🇲🇩 +373 Moldova', code: '+373', flag:'🇲🇩', country: 'MD' },
    { text: '🇦🇲 +374 Armenia', code: '+374', flag:'🇦🇲', country: 'AM' },
    { text: '🇧🇾 +375 Belarus', code: '+375', flag:'🇧🇾', country: 'BY' },
    { text: '🇦🇩 +376 Andorra', code: '+376',flag:'🇦🇩',  country: 'AD' },
    { text: '🇲🇨 +377 Monaco', code: '+377', flag:'🇲🇨', country: 'MC' },
    { text: '🇸🇲 +378 San Marino', code: '+378', flag:'🇸🇲', country: 'SM' },
    { text: '🇺🇦 +380 Ukraine', code: '+380', flag:'🇺🇦', country: 'UA' },
    { text: '🇷🇸 +381 Serbia', code: '+381', flag:'🇷🇸', country: 'RS' },
    { text: '🇲🇪 +382 Montenegro', code: '+382', flag:'🇲🇪', country: 'ME' },
    { text: '🇭🇷 +385 Croatia', code: '+385', flag:'🇭🇷', country: 'HR' },
    { text: '🇸🇮 +386 Slovenia', code: '+386', flag:'🇸🇮', country: 'SI' },
    { text: '🇧🇦 +387 Bosnia and Herzegovina', code: '+387', flag:'🇧🇦', country: 'BA' },
    { text: '🇲🇰 +389 North Macedonia', code: '+389', flag:'🇲🇰', country: 'MK' },
    { text: '🇨🇿 +420 Czech Republic', code: '+420', flag:'🇨🇿', country: 'CZ' },
    { text: '🇸🇰 +421 Slovakia', code: '+421', flag:'🇸🇰', country: 'SK' },
    { text: '🇱🇮 +423 Liechtenstein', code: '+423', flag:'🇱🇮', country: 'LI' },
    { text: '🇫🇰 +500 Falkland Islands', code: '+500', flag:'🇫🇰', country: 'FK' },
    { text: '🇧🇿 +501 Belize', code: '+501', flag:'🇧🇿', country: 'BZ' },
    { text: '🇬🇹 +502 Guatemala', code: '+502', flag:'🇬🇹', country: 'GT' },
    { text: '🇸🇻 +503 El Salvador', code: '+503', flag:'🇸🇻', country: 'SV' },
    { text: '🇭🇳 +504 Honduras', code: '+504', flag:'🇭🇳', country: 'HN' },
    { text: '🇳🇮 +505 Nicaragua', code: '+505', flag:'🇳🇮', country: 'NI' },
    { text: '🇨🇷 +506 Costa Rica', code: '+506', flag:'🇨🇷', country: 'CR' },
    { text: '🇵🇦 +507 Panama', code: '+507', flag:'🇵🇦', country: 'PA' },
    { text: '🇵🇲 +508 Saint Pierre and Miquelon', code: '+508', flag:'🇵🇲', country: 'PM' },
    { text: '🇭🇹 +509 Haiti', code: '+509', flag:'🇭🇹', country: 'HT' },
    { text: '🇬🇵 +590 Guadeloupe', code: '+590', flag:'🇬🇵', country: 'GP' },
    { text: '🇧🇴 +591 Bolivia', code: '+591', flag:'🇧🇴', country: 'BO' },
    { text: '🇬🇾 +592 Guyana', code: '+592', flag:'🇬🇾', country: 'GY' },
    { text: '🇪🇨 +593 Ecuador', code: '+593', flag:'🇪🇨', country: 'EC' },
    { text: '🇬🇫 +594 French Guiana', code: '+594', flag:'🇬🇫', country: 'GF' },
    { text: '🇵🇾 +595 Paraguay', code: '+595', flag:'🇵🇾', country: 'PY' },
    { text: '🇲🇶 +596 Martinique', code: '+596', flag:'🇲🇶', country: 'MQ' },
    { text: '🇸🇷 +597 Suriname', code: '+597', flag:'🇸🇷', country: 'SR' },
    { text: '🇺🇾 +598 Uruguay', code: '+598', flag:'🇺🇾', country: 'UY' },
    { text: '🇨🇼 +599 Curaçao', code: '+599', flag:'🇨🇼', country: 'CW' },
    { text: '🇹🇱 +670 Timor-Leste', code: '+670', flag:'🇹🇱', country: 'TL' },
    { text: '🇦🇶 +672 Antarctica', code: '+672', flag:'🇦🇶', country: 'AQ' },
    { text: '🇧🇳 +673 Brunei', code: '+673', flag:'🇧🇳', country: 'BN' },
    { text: '🇳🇷 +674 Nauru', code: '+674', flag:'🇳🇷', country: 'NR' },
    { text: '🇵🇬 +675 Papua New Guinea', code: '+675', flag:'🇵🇬', country: 'PG' },
    { text: '🇹🇴 +676 Tonga', code: '+676', flag:'🇹🇴', country: 'TO' },
    { text: '🇸🇧 +677 Solomon Islands', code: '+677', flag:'🇸🇧', country: 'SB' },
    { text: '🇻🇺 +678 Vanuatu', code: '+678', flag:'🇻🇺', country: 'VU' },
    { text: '🇫🇯 +679 Fiji', code: '+679', flag:'🇫🇯', country: 'FJ' },
    { text: '🇵🇼 +680 Palau', code: '+680', flag:'🇵🇼', country: 'PW' },
    { text: '🇼🇫 +681 Wallis and Futuna', code: '+681', flag:'🇼🇫', country: 'WF' },
    { text: '🇨🇰 +682 Cook Islands', code: '+682', flag:'🇨🇰', country: 'CK' },
    { text: '🇳🇺 +683 Niue', code: '+683', flag:'🇳🇺', country: 'NU' },
    { text: '🇼🇸 +685 Samoa', code: '+685', flag:'🇼🇸', country: 'WS' },
    { text: '🇰🇮 +686 Kiribati', code: '+686', flag:'🇰🇮', country: 'KI' },
    { text: '🇳🇨 +687 New Caledonia', code: '+687', flag:'🇳🇨', country: 'NC' },
    { text: '🇹🇻 +688 Tuvalu', code: '+688', flag:'🇹🇻', country: 'TV' },
    { text: '🇵🇫 +689 French Polynesia', code: '+689', flag:'🇵🇫', country: 'PF' },
    { text: '🇹🇰 +690 Tokelau', code: '+690', flag:'🇹🇰', country: 'TK' },
    { text: '🇫🇲 +691 Federated States of Micronesia', code: '+691', flag:'🇫🇲', country: 'FM' },
    { text: '🇲🇭 +692 Marshall Islands', code: '+692', flag:'🇲🇭', country: 'MH' },
    { text: '🇰🇵 +850 North Korea', code: '+850', flag:'🇰🇵', country: 'KP' },
    { text: '🇭🇰 +852 Hong Kong', code: '+852', flag:'🇭🇰', country: 'HK' },
    { text: '🇲🇴 +853 Macau', code: '+853', flag:'🇲🇴', country: 'MO' },
    { text: '🇰🇭 +855 Cambodia', code: '+855', flag:'🇰🇭', country: 'KH' },
    { text: '🇱🇦 +856 Laos', code: '+856', flag:'🇱🇦', country: 'LA' },
    { text: '🇧🇩 +880 Bangladesh', code: '+880', flag:'🇧🇩', country: 'BD' },
    { text: '🇹🇼 +886 Taiwan', code: '+886', flag:'🇹🇼', country: 'TW' },
    { text: '🇲🇻 +960 Maldives', code: '+960', flag:'🇲🇻', country: 'MV' },
    { text: '🇱🇧 +961 Lebanon', code: '+961', flag:'🇱🇧', country: 'LB' },
    { text: '🇯🇴 +962 Jordan', code: '+962', flag:'🇯🇴', country: 'JO' },
    { text: '🇸🇾 +963 Syria', code: '+963', flag:'🇸🇾', country: 'SY' },
    { text: '🇮🇶 +964 Iraq', code: '+964', flag:'🇮🇶', country: 'IQ' },
    { text: '🇰🇼 +965 Kuwait', code: '+965', flag:'🇰🇼', country: 'KW' },
    { text: '🇸🇦 +966 Saudi Arabia', code: '+966', flag:'🇸🇦', country: 'SA' },
    { text: '🇾🇪 +967 Yemen', code: '+967', flag:'🇾🇪', country: 'YE' },
    { text: '🇴🇲 +968 Oman', code: '+968', flag:'🇴🇲', country: 'OM' },
    { text: '🇵🇸 +970 Palestine', code: '+970', flag:'🇵🇸', country: 'PS' },
    { text: '🇦🇪 +971 United Arab Emirates', code: '+971', flag:'🇦🇪', country: 'AE' },
    { text: '🇮🇱 +972 Israel', code: '+972', flag:'🇮🇱', country: 'IL' },
    { text: '🇧🇭 +973 Bahrain', code: '+973', flag:'🇧🇭', country: 'BH' },
    { text: '🇶🇦 +974 Qatar', code: '+974', flag:'🇶🇦', country: 'QA' },
    { text: '🇧🇹 +975 Bhutan', code: '+975', flag:'🇧🇹', country: 'BT' },
    { text: '🇲🇳 +976 Mongolia', code: '+976', flag:'🇲🇳', country: 'MN' },
    { text: '🇳🇵 +977 Nepal', code: '+977', flag:'🇳🇵', country: 'NP' },
    { text: '🇹🇯 +992 Tajikistan', code: '+992', flag:'🇹🇯', country: 'TJ' },
    { text: '🇹🇲 +993 Turkmenistan', code: '+993', flag:'🇹🇲', country: 'TM' },
    { text: '🇦🇿 +994 Azerbaijan', code: '+994', flag:'🇦🇿', country: 'AZ' },
    { text: '🇬🇪 +995 Georgia', code: '+995', flag:'🇬🇪', country: 'GE' },
    { text: '🇰🇬 +996 Kyrgyzstan', code: '+996', flag:'🇰🇬', country: 'KG' },
    { text: '🇺🇿 +998 Uzbekistan', code: '+998', flag:'🇺🇿', country: 'UZ' },
]

export const countries = [
    {"name": "Afghanistan", "code": "AF"},
    {"name": "Åland Islands", "code": "AX"},
    {"name": "Albania", "code": "AL"},
    {"name": "Algeria", "code": "DZ"},
    {"name": "American Samoa", "code": "AS"},
    {"name": "AndorrA", "code": "AD"},
    {"name": "Angola", "code": "AO"},
    {"name": "Anguilla", "code": "AI"},
    {"name": "Antarctica", "code": "AQ"},
    {"name": "Antigua and Barbuda", "code": "AG"},
    {"name": "Argentina", "code": "AR"},
    {"name": "Armenia", "code": "AM"},
    {"name": "Aruba", "code": "AW"},
    {"name": "Australia", "code": "AU"},
    {"name": "Austria", "code": "AT"},
    {"name": "Azerbaijan", "code": "AZ"},
    {"name": "Bahamas", "code": "BS"},
    {"name": "Bahrain", "code": "BH"},
    {"name": "Bangladesh", "code": "BD"},
    {"name": "Barbados", "code": "BB"},
    {"name": "Belarus", "code": "BY"},
    {"name": "Belgium", "code": "BE"},
    {"name": "Belize", "code": "BZ"},
    {"name": "Benin", "code": "BJ"},
    {"name": "Bermuda", "code": "BM"},
    {"name": "Bhutan", "code": "BT"},
    {"name": "Bolivia", "code": "BO"},
    {"name": "Bosnia and Herzegovina", "code": "BA"},
    {"name": "Botswana", "code": "BW"},
    {"name": "Bouvet Island", "code": "BV"},
    {"name": "Brazil", "code": "BR"},
    {"name": "British Indian Ocean Territory", "code": "IO"},
    {"name": "Brunei Darussalam", "code": "BN"},
    {"name": "Bulgaria", "code": "BG"},
    {"name": "Burkina Faso", "code": "BF"},
    {"name": "Burundi", "code": "BI"},
    {"name": "Cambodia", "code": "KH"},
    {"name": "Cameroon", "code": "CM"},
    {"name": "Canada", "code": "CA"},
    {"name": "Cape Verde", "code": "CV"},
    {"name": "Cayman Islands", "code": "KY"},
    {"name": "Central African Republic", "code": "CF"},
    {"name": "Chad", "code": "TD"},
    {"name": "Chile", "code": "CL"},
    {"name": "China", "code": "CN"},
    {"name": "Christmas Island", "code": "CX"},
    {"name": "Cocos (Keeling) Islands", "code": "CC"},
    {"name": "Colombia", "code": "CO"},
    {"name": "Comoros", "code": "KM"},
    {"name": "Congo", "code": "CG"},
    {"name": "Congo, The Democratic Republic of the", "code": "CD"},
    {"name": "Cook Islands", "code": "CK"},
    {"name": "Costa Rica", "code": "CR"},
    {"name": "Cote D\"Ivoire", "code": "CI"},
    {"name": "Croatia", "code": "HR"},
    {"name": "Cuba", "code": "CU"},
    {"name": "Cyprus", "code": "CY"},
    {"name": "Czech Republic", "code": "CZ"},
    {"name": "Denmark", "code": "DK"},
    {"name": "Djibouti", "code": "DJ"},
    {"name": "Dominica", "code": "DM"},
    {"name": "Dominican Republic", "code": "DO"},
    {"name": "Ecuador", "code": "EC"},
    {"name": "Egypt", "code": "EG"},
    {"name": "El Salvador", "code": "SV"},
    {"name": "Equatorial Guinea", "code": "GQ"},
    {"name": "Eritrea", "code": "ER"},
    {"name": "Estonia", "code": "EE"},
    {"name": "Ethiopia", "code": "ET"},
    {"name": "Falkland Islands (Malvinas)", "code": "FK"},
    {"name": "Faroe Islands", "code": "FO"},
    {"name": "Fiji", "code": "FJ"},
    {"name": "Finland", "code": "FI"},
    {"name": "France", "code": "FR"},
    {"name": "French Guiana", "code": "GF"},
    {"name": "French Polynesia", "code": "PF"},
    {"name": "French Southern Territories", "code": "TF"},
    {"name": "Gabon", "code": "GA"},
    {"name": "Gambia", "code": "GM"},
    {"name": "Georgia", "code": "GE"},
    {"name": "Germany", "code": "DE"},
    {"name": "Ghana", "code": "GH"},
    {"name": "Gibraltar", "code": "GI"},
    {"name": "Greece", "code": "GR"},
    {"name": "Greenland", "code": "GL"},
    {"name": "Grenada", "code": "GD"},
    {"name": "Guadeloupe", "code": "GP"},
    {"name": "Guam", "code": "GU"},
    {"name": "Guatemala", "code": "GT"},
    {"name": "Guernsey", "code": "GG"},
    {"name": "Guinea", "code": "GN"},
    {"name": "Guinea-Bissau", "code": "GW"},
    {"name": "Guyana", "code": "GY"},
    {"name": "Haiti", "code": "HT"},
    {"name": "Heard Island and Mcdonald Islands", "code": "HM"},
    {"name": "Holy See (Vatican City State)", "code": "VA"},
    {"name": "Honduras", "code": "HN"},
    {"name": "Hong Kong", "code": "HK"},
    {"name": "Hungary", "code": "HU"},
    {"name": "Iceland", "code": "IS"},
    {"name": "India", "code": "IN"},
    {"name": "Indonesia", "code": "ID"},
    {"name": "Iran, Islamic Republic Of", "code": "IR"},
    {"name": "Iraq", "code": "IQ"},
    {"name": "Ireland", "code": "IE"},
    {"name": "Isle of Man", "code": "IM"},
    {"name": "Israel", "code": "IL"},
    {"name": "Italy", "code": "IT"},
    {"name": "Jamaica", "code": "JM"},
    {"name": "Japan", "code": "JP"},
    {"name": "Jersey", "code": "JE"},
    {"name": "Jordan", "code": "JO"},
    {"name": "Kazakhstan", "code": "KZ"},
    {"name": "Kenya", "code": "KE"},
    {"name": "Kiribati", "code": "KI"},
    {"name": "Korea, Democratic People\"S Republic of", "code": "KP"},
    {"name": "Korea, Republic of", "code": "KR"},
    {"name": "Kuwait", "code": "KW"},
    {"name": "Kyrgyzstan", "code": "KG"},
    {"name": "Lao People\"S Democratic Republic", "code": "LA"},
    {"name": "Latvia", "code": "LV"},
    {"name": "Lebanon", "code": "LB"},
    {"name": "Lesotho", "code": "LS"},
    {"name": "Liberia", "code": "LR"},
    {"name": "Libyan Arab Jamahiriya", "code": "LY"},
    {"name": "Liechtenstein", "code": "LI"},
    {"name": "Lithuania", "code": "LT"},
    {"name": "Luxembourg", "code": "LU"},
    {"name": "Macao", "code": "MO"},
    {"name": "Macedonia, The Former Yugoslav Republic of", "code": "MK"},
    {"name": "Madagascar", "code": "MG"},
    {"name": "Malawi", "code": "MW"},
    {"name": "Malaysia", "code": "MY"},
    {"name": "Maldives", "code": "MV"},
    {"name": "Mali", "code": "ML"},
    {"name": "Malta", "code": "MT"},
    {"name": "Marshall Islands", "code": "MH"},
    {"name": "Martinique", "code": "MQ"},
    {"name": "Mauritania", "code": "MR"},
    {"name": "Mauritius", "code": "MU"},
    {"name": "Mayotte", "code": "YT"},
    {"name": "Mexico", "code": "MX"},
    {"name": "Micronesia, Federated States of", "code": "FM"},
    {"name": "Moldova, Republic of", "code": "MD"},
    {"name": "Monaco", "code": "MC"},
    {"name": "Mongolia", "code": "MN"},
    {"name": "Montserrat", "code": "MS"},
    {"name": "Morocco", "code": "MA"},
    {"name": "Mozambique", "code": "MZ"},
    {"name": "Myanmar", "code": "MM"},
    {"name": "Namibia", "code": "NA"},
    {"name": "Nauru", "code": "NR"},
    {"name": "Nepal", "code": "NP"},
    {"name": "Netherlands", "code": "NL"},
    {"name": "Netherlands Antilles", "code": "AN"},
    {"name": "New Caledonia", "code": "NC"},
    {"name": "New Zealand", "code": "NZ"},
    {"name": "Nicaragua", "code": "NI"},
    {"name": "Niger", "code": "NE"},
    {"name": "Nigeria", "code": "NG"},
    {"name": "Niue", "code": "NU"},
    {"name": "Norfolk Island", "code": "NF"},
    {"name": "Northern Mariana Islands", "code": "MP"},
    {"name": "Norway", "code": "NO"},
    {"name": "Oman", "code": "OM"},
    {"name": "Pakistan", "code": "PK"},
    {"name": "Palau", "code": "PW"},
    {"name": "Palestinian Territory, Occupied", "code": "PS"},
    {"name": "Panama", "code": "PA"},
    {"name": "Papua New Guinea", "code": "PG"},
    {"name": "Paraguay", "code": "PY"},
    {"name": "Peru", "code": "PE"},
    {"name": "Philippines", "code": "PH"},
    {"name": "Pitcairn", "code": "PN"},
    {"name": "Poland", "code": "PL"},
    {"name": "Portugal", "code": "PT"},
    {"name": "Puerto Rico", "code": "PR"},
    {"name": "Qatar", "code": "QA"},
    {"name": "Reunion", "code": "RE"},
    {"name": "Romania", "code": "RO"},
    {"name": "Russian Federation", "code": "RU"},
    {"name": "RWANDA", "code": "RW"},
    {"name": "Saint Helena", "code": "SH"},
    {"name": "Saint Kitts and Nevis", "code": "KN"},
    {"name": "Saint Lucia", "code": "LC"},
    {"name": "Saint Pierre and Miquelon", "code": "PM"},
    {"name": "Saint Vincent and the Grenadines", "code": "VC"},
    {"name": "Samoa", "code": "WS"},
    {"name": "San Marino", "code": "SM"},
    {"name": "Sao Tome and Principe", "code": "ST"},
    {"name": "Saudi Arabia", "code": "SA"},
    {"name": "Senegal", "code": "SN"},
    {"name": "Serbia and Montenegro", "code": "CS"},
    {"name": "Seychelles", "code": "SC"},
    {"name": "Sierra Leone", "code": "SL"},
    {"name": "Singapore", "code": "SG"},
    {"name": "Slovakia", "code": "SK"},
    {"name": "Slovenia", "code": "SI"},
    {"name": "Solomon Islands", "code": "SB"},
    {"name": "Somalia", "code": "SO"},
    {"name": "South Africa", "code": "ZA"},
    {"name": "South Georgia and the South Sandwich Islands", "code": "GS"},
    {"name": "Spain", "code": "ES"},
    {"name": "Sri Lanka", "code": "LK"},
    {"name": "Sudan", "code": "SD"},
    {"name": "Suriname", "code": "SR"},
    {"name": "Svalbard and Jan Mayen", "code": "SJ"},
    {"name": "Swaziland", "code": "SZ"},
    {"name": "Sweden", "code": "SE"},
    {"name": "Switzerland", "code": "CH"},
    {"name": "Syrian Arab Republic", "code": "SY"},
    {"name": "Taiwan", "code": "TW"},
    {"name": "Tajikistan", "code": "TJ"},
    {"name": "Tanzania, United Republic of", "code": "TZ"},
    {"name": "Thailand", "code": "TH"},
    {"name": "Timor-Leste", "code": "TL"},
    {"name": "Togo", "code": "TG"},
    {"name": "Tokelau", "code": "TK"},
    {"name": "Tonga", "code": "TO"},
    {"name": "Trinidad and Tobago", "code": "TT"},
    {"name": "Tunisia", "code": "TN"},
    {"name": "Turkey", "code": "TR"},
    {"name": "Turkmenistan", "code": "TM"},
    {"name": "Turks and Caicos Islands", "code": "TC"},
    {"name": "Tuvalu", "code": "TV"},
    {"name": "Uganda", "code": "UG"},
    {"name": "Ukraine", "code": "UA"},
    {"name": "United Arab Emirates", "code": "AE"},
    {"name": "United Kingdom", "code": "GB"},
    {"name": "United States", "code": "US"},
    {"name": "United States Minor Outlying Islands", "code": "UM"},
    {"name": "Uruguay", "code": "UY"},
    {"name": "Uzbekistan", "code": "UZ"},
    {"name": "Vanuatu", "code": "VU"},
    {"name": "Venezuela", "code": "VE"},
    {"name": "Viet Nam", "code": "VN"},
    {"name": "Virgin Islands, British", "code": "VG"},
    {"name": "Virgin Islands, U.S.", "code": "VI"},
    {"name": "Wallis and Futuna", "code": "WF"},
    {"name": "Western Sahara", "code": "EH"},
    {"name": "Yemen", "code": "YE"},
    {"name": "Zambia", "code": "ZM"},
    {"name": "Zimbabwe", "code": "ZW"}
]