export const environment = {
    BASE_URL: 'http://localhost:8004',
    isProduction: false,
    PAYMENT_URL: '/revenue',
    LEGACY_PREFIX: '',
    //API_PORT: 8632,
    //API_PORT: 8004,
    //API ENDPOINTS
    PRODUCT_CATALOG: '/catalog',
    SERVICE: '/service',
    RESOURCE: '/resource',
    PRODUCT_SPEC: '/productSpecification',
    SERVICE_SPEC: '/serviceSpecification',
    RESOURCE_SPEC: '/resourceSpecification',
    ACCOUNT: '/account',
    SHOPPING_CART: '/shoppingCart',
    INVENTORY: '/inventory',
    PRODUCT_ORDER: '/ordering',
    CHARGING: '/charging',
    BILLING: '/billing',

    searchOrganizationsEndpoint: 'http://dome-search-svc.search-engine.svc.cluster.local:8080/api/searchOrganizations',

    CUSTOMER_BILLING:'/customerBill',
    CONSUMER_BILLING_URL: 'http://localhost:8640',
    //API PAGINATION
    PRODUCT_LIMIT: 6,
    CATALOG_LIMIT: 8,
    INVENTORY_LIMIT: 6,
    INVENTORY_RES_LIMIT: 6,
    INVENTORY_SERV_LIMIT: 6,
    PROD_SPEC_LIMIT: 6,
    SERV_SPEC_LIMIT: 6,
    RES_SPEC_LIMIT: 6,
    USAGE_SPEC_LIMIT: 6,
    ORDER_LIMIT: 1000,
    CATEGORY_LIMIT: 100,
    INVOICE_LIMIT: 100,
    SIOP: false,
    TAX_RATE: 20,
    CHAT_API: 'https://85.215.243.214:5000/predict',
    SIOP_INFO: {
        enabled: false,
        isRedirection: false,
        pollPath: "",
        pollCertPath: "",
        clientID: "",
        callbackURL: "",
        verifierHost: "",
        verifierQRCodePath: "",
        requestUri: ""
    },
    MATOMO_TRACKER_URL: "",
    MATOMO_SITE_ID: "",
    TICKETING_SYSTEM_URL: "",
    KNOWLEDGE_BASE_URL: "",
    KB_ONBOARDING_GUIDELINES_URL: "https://knowledgebase.dome-marketplace-prd.org/books/company-onboarding-process-guide-for-cloud-service-providers-csp",
    KB_GUIDELNES_URL:"https://knowledgebase.dome-marketplace-prd.org/books/managing-orders-products-and-subscriptions",
    REGISTRATION_FORM_URL: "https://onboarding.dome-marketplace.eu/",
    SEARCH_ENABLED: true,
    PURCHASE_ENABLED: false,
    DOME_TRUST_LINK: "https://dome-certification.dome-marketplace.org",
    DOME_ABOUT_LINK: '',
    DOME_REGISTER_LINK: '',
    DOME_PUBLISH_LINK:'',
    DOME_LINKEDIN: 'https://www.linkedin.com/company/dome-marketplace/',
    DOME_YOUTUBE: 'https://www.youtube.com/channel/UC8UiL59S0JiaYYr14w5eOzA',
    DOME_X: 'https://x.com/DomeMarketplace',
    BUNDLE_ENABLED: false,
    DFT_CATALOG_ID: '',
    MAX_FILE_SIZE:3145728,
    providerThemeName: 'default',
    quoteApi: 'http://localhost:8080/quoteManagement',
    quoteEndpoints: {
        createQuote: '/createQuote',
        listAllQuotes: '/listAllQuotes',
        getQuoteById: '/quoteById',
        getQuotesByUser: '/quoteByUser',
        updateQuoteStatus: '/updateQuoteStatus',
        updateQuoteDate: '/updateQuoteDate',
        addNoteToQuote: '/addNoteToQuote',
        addAttachmentToQuote: '/addAttachmentToQuote',
        deleteQuote: '/quote'
    },
    QUOTES_ENABLED: true,
    analytics: '',
    feedbackCampaign: false,
    feedbackCampaignExpiration: 0,
    SELLER_ROLE: 'Seller',
    BUYER_ROLE: 'Buyer',
    ADMIN_ROLE: 'Admin',
    ORG_ADMIN_ROLE: 'orgAdmin',
    CERTIFIER_ROLE: 'certifier'
};
